
const ITEMS_C = [
    {
        session: 'background',
        name:'background',
        itemPos: {x: 0, y: -0.03},
        mobilePos: {x: -0.05, y: -0.03},
        itemShadowDir: [0, 0],
        page: 2,
        itemShadowY: 0,
        size: 0.8,
        zOrder: 0,
        anchor: [0,0],
    },
    {
        session: 'background',
        name:'floor',
        page: 2,
        itemPos: {x: -0.04, y: 0.4},
        mobilePos: {x: -0.07, y: 0.4},
        itemShadowDir: [0, 0],
        itemShadowY: 1,
        size: 1,
        zOrder: 0,
        anchor: [0,-0.1],
        anchorMobile: [0,0],
    },
    {
        session: 'background',
        name:'mangaShelf',
        page: 2,
        itemPos: {x: 0.52, y: 0.1},
        mobilePos: {x: 0.52, y: 0.05},
        itemShadowDir: [-0.02, 1.02],
        itemShadowY: 1.1,
        size: 0.4,
        zOrder: 0,
        anchor: [0,0],
    },
    {
        session: 'yoga',
        name: 'yoga',
        avatarAnim: 'yoga',
        scene: 1,
        page: 1,
        itemPos: {x: 0.3, y: 0.55},
        avatarPos: {x: 0.29, y: 0.55},
        mobilePos: {x: 0.3, y: 0.58},
        itemShadowDir: [0.1, 0.1],
        itemShadowY: 0.5,
        avatarShadowDir: [-0.1, -0.3],
        avatarShadowY: 0.08,
        size: 0.48,
        clickable: true,
        zOrder: 2,
        anchor: [0.5,0],
        anchorMobile: [0.5, 0],
        hitAreaOffset: [-80, -60, 200, 130],
    },
    {
        session: 'piano',
        name: 'piano',
        avatarAnim: 'piano',
        page: 1,
        scene: 1,
        itemPos: {x: 0.5, y: 0.7},
        avatarPos: {x: 0.38, y: 0.75},
        mobilePos: {x: 0.3, y: 0.8},
        itemShadowDir: [0.9, -0.9],
        itemShadowY: 0.22,
        avatarShadowDir:[0.2, -0.3],
        avatarShadowY: 0.01,
        size: 0.65,
        clickable: true,
        anchor: [1, 0.5],
        anchorMobile: [0, 0.6],
        hitAreaOffset: [-60, -140, 100, 170],
    },
    {
        session: 'computerChewy',
        name: 'computerChewy',
        avatarAnim: 'computer',
        subAssetsName: 'page_chewy',
        subAssetsOffset: {x: -480, y: 0},
        scene: 1,
        page: 2,
        itemPos: {x: 0.55, y: 0.58},
        avatarPos: {x: 0.68, y: 0.57},
        mobilePos: {x: 0.73, y: 0.65},
        itemShadowDir: [-0.4, 0.2],
        itemShadowY: 0.35,
        avatarShadowDir: [0.2, -0.1],
        avatarShadowY: 0.21,
        size: 0.4,
        zOrder: 0,
        hasAnim: true,
        anchor: [0, 0.5],
        clickable: true,
        anchorMobile: [0.75, 0.5],
        hitAreaOffset:  [-50, -130, 100, 150],
    },
    {
        session: 'computerChewy',
        name:'chair',
        page: 2,
        scene: 0,
        itemPos: {x: 0.71, y: 0.63},
        mobilePos: {x: 0.8, y: 0.7},
        itemShadowDir: [0.2, 0.1],
        itemShadowY: 0.47,
        size: 0.48,
        interaction: 'fade',
        zOrder: 0,
        anchor: [0.5, 0.5],
    },
];

const ITEMS_S = [
    {
        session: 'background',
        name:'frameShelf',
        page: 1,
        itemShadowDir: [-0.02, 1.02],
        itemShadowY: 1.1,
        itemPos: {x: 0.07, y: 0.13},
        mobilePos: {x: 0.07, y: 0.115},
        size: 0.35,
        zOrder: 0,
        anchor: [0,0],
    },
    {
        session: 'window',
        name:'window',
        page: 1,
        itemPos: {x: 0.23, y: 0.1},
        mobilePos: {x: 0.3, y: 0.12},
        itemShadowDir: [0, 1.1],
        itemShadowY: 0.3,
        size: 0.3,
        zOrder: 0,
        anchor: 0,
    },

    {
        session: 'background',
        name:'toolShelf',
        page: 2,
        itemShadowDir: [0.02, 1.05],
        itemShadowY: 1.1,
        itemPos: {x: 1, y: 0.06},
        mobilePos: {x: 1, y: 0.1},
        size: 0.35,
        zOrder: 0,
        anchor: [1,0],
    },
   
    {
        session: 'bed',
        name: 'bed',
        avatarAnim: 'bedtime',
        page: 1,
        scene: 0,
        itemPos: {x: 0.113, y: 0.6},
        avatarPos: {x: 0.11, y: 0.55},
        mobilePos: {x: 0.18, y: 0.43},
        itemShadowDir: [-0.5, -0.7],
        itemShadowY: 0.2,
        avatarShadowDir:[-0.4, -0.3],
        avatarShadowY: 0.06,
        size: 0.5,
        clickable: true,
        zOrder: 0,
        anchor: [0.5, 0.5],
        anchorMobile: [0.5, 0.4],
        hitAreaOffset: [-120, -70, 250, 130],
    },
    {
        session: 'guitar',
        name: 'guitar',
        avatarAnim: 'guitar',
        page: 1,
        scene: 0,
        itemPos: {x: 0.15, y: 0.7},
        avatarPos: {x: 0.15, y: 0.65},
        mobilePos: {x: 0.12, y: 0.75},
        itemShadowDir: [0.4, -0.3],
        itemShadowY: 0.4,
        avatarShadowDir: [-0.1, -0.3],
        avatarShadowY: 0.24,
        size: 0.42,
        clickable: true,
        interaction: 'fade',
        zOrder: 2,
        anchor: [0.5,0.5],
        anchorMobile: [0.5,0.2],
        hitAreaOffset: [-40, -40, 90, 160],
    },

    {
        session: 'computer',
        name: 'computer',
        avatarAnim: 'computer',
        subAssetsName: 'sites',
        subAssetsOffset: {x: 400, y: 0},
        page: 2,
        scene: 0,
        itemPos: {x: 1, y: 0.52},
        avatarPos: {x: 0.88, y: 0.52},
        mobilePos: {x: 0.82, y: 0.38},
        itemShadowDir: [0.5, 0.2],
        itemShadowY: 0.44,
        avatarShadowDir: [0.2, -0.1],
        avatarShadowY: 0.28,
        size: 0.4,
        zOrder: 0,
        hasAnim: true,
        anchor: [1, 0.5],
        anchorMobile: [0.5, 0.5],
        clickable: true,
        hitAreaOffset:  [-50, -120, 100, 180],
    },
    {
        session: 'computer',
        page: 2,
        name:'chair',
        scene: 0,
        itemPos: {x: 0.9, y: 0.65},
        mobilePos: {x: 0.85, y: 0.45},
        itemShadowDir: [0.5, 0.2],
        itemShadowY: 0.44,
        size: 0.4,
        interaction: 'fade',
        zOrder: 0,
        anchor: [1, 0.5],
    },
    {
        session: 'pizza',
        name: 'pizza',
        avatarAnim: 'pizza',
        page: 2,
        scene: 0,
        itemPos: {x: 0.85, y: 0.89},
        mobilePos: {x: 0.75, y: 0.88},
        itemShadowDir: [0.4, 0.3],
        itemShadowY: -0.1,
        avatarPos: {x: 0.84, y: 0.8},
        avatarShadowDir: [0.2, -0.3],
        avatarShadowY: 0.08,
        hitAreaOffset:  [-110, -120, 90, 150],
        size: 0.4,
        clickable: true,
        zOrder: 2,
        anchor: [0.5, 0.5],
        anchorMobile: [0.2, 0.1],
    },
];

const OTHERS = [
    {
        name:'letter',
        itemShadowDir: [-0.02, 1.02],
        itemShadowY: 1.1,
        itemPos: {x: 0.075, y: 0.09},
        mobilePos: {x: 0.08, y: 0.07},
        size: 0.1,
        zOrder: 0,
        anchor: 0,
    },
    {
        name: 'angel_stephen',
        avatarAnim: 'hug',
        mobilePos: {x: 0.19, y: 0.75},
        mobilePos2: {x: 0.7, y: 0.75},
        avatarPos: {x: 0.2, y: 0.7},
        avatarPos2: {x: 0.73, y: 0.7},
        avatarShadowDir: [0, -0.3],
        avatarShadowY: 0.2,
        size: 0.8,
        anchor: 0.5,
    },
    {
        name: 'angel_chewy',
        avatarAnim: 'hug',
        mobilePos: {x: 0.15, y: 0.75},
        mobilePos2: {x: 0.65, y: 0.75},
        avatarPos: {x: 0.18, y: 0.8},
        avatarPos2: {x: 0.68, y: 0.8},
        avatarShadowDir: [0, -0.3],
        avatarShadowY: 0.2,
        size: 0.8,
        anchor: 0.5,
    },
]
    
export {ITEMS_S, ITEMS_C, OTHERS}