const ITEMS = [
    {
        session: 'background',
        name:'background',
        scene: 0,
        itemPos: {x: 0, y: 0},
        itemShadowDir: [0, 0],
        itemShadowY: 0,
        size: 0.8,
        zOrder: 0,
        anchor: 0,
    },
    {
        session: 'background',
        name:'floor',
        scene: 0,
        itemPos: {x: 0, y: 0.7},
        itemShadowDir: [0, 0],
        itemShadowY: 0,
        size: 0.75,
        zOrder: 0,
        anchor: 0,
    },
    {
        session: 'background',
        name:'frameShelf',
        itemShadowDir: [-0.02, 1.02],
        itemShadowY: 1.1,
        scene: 0,
        itemPos: {x: 0.1, y: 0.13},
        size: 0.7,
        zOrder: 0,
        anchor: 0,
    },

    {
        session: 'background',
        name:'toolShelf',
        itemShadowDir: [0.02, 1.05],
        itemShadowY: 1.1,
        scene: 0,
        itemPos: {x: 0.6, y: 0.05},
        size: 0.7,
        zOrder: 0,
        anchor: 0,
    },
    {
        session: 'window',
        name:'window',
        scene: 0,
        itemPos: {x: 0.37, y: 0.1},
        itemShadowDir: [0, 1.1],
        itemShadowY: 0.3,
        size: 0.6,
        zOrder: 0,
        anchor: 0,
    },

    {
        session: 'bed',
        name: 'bed',
        avatarAnim: 'bedtime',
        scene: 0,
        itemPos: {x: 0.21, y: 0.75},
        itemShadowDir: [-0.5, -0.8],
        itemShadowY: 0.2,
        avatarPos: {x: 0.2, y: 0.7},
        avatarShadowDir:[-0.4, -0.3],
        avatarShadowY: 0.1,
        size: 0.85,
        clickable: true,
        zOrder: 0,
        anchor: 0.5,
        hitAreaOffset: [-150, -100, 300, 180],
    },
    {
        session: 'guitar',
        name: 'guitar',
        avatarAnim: 'guitar',
        scene: 0,
        itemPos: {x: 0.35, y: 0.5},
        itemShadowDir: [0.2, -0.2],
        itemShadowY: 0.97,
        avatarPos: {x: 0.44, y: 0.6},
        avatarShadowDir: [-0.1, -0.3],
        avatarShadowY: 0.35,
        size: 0.7,
        clickable: true,
        interaction: 'fade',
        zOrder: 2,
        anchor: 0,
        hitAreaOffset: [-80, -80, 180, 300],
    },

    {
        session: 'computer',
        name: 'computer',
        avatarAnim: 'computer',
        subAssetsName: 'sites',
        scene: 0,
        itemPos: {x: 0.77, y: 0.61},
        itemShadowDir: [0.5, 0.2],
        itemShadowY: 0.44,
        avatarPos: {x: 0.77, y: 0.6},
        avatarShadowDir: [0.2, -0.2],
        avatarShadowY: 0.47,
        size: 0.8,
        zOrder: 0,
        hasAnim: true,
        anchor: 0.5,
        clickable: true,
        hitAreaOffset:  [-80, -180, 180, 300],
    },
    {
        session: 'computer',
        name:'chair',
        scene: 0,
        itemPos: {x: 0.7, y: 0.7},
        itemShadowDir: [0.5, 0.2],
        itemShadowY: 0.44,
        size: 0.8,
        interaction: 'fade',
        zOrder: 0,
        anchor: 0.5,
    },
    {
        session: 'pizza',
        name: 'pizza',
        avatarAnim: 'pizza',
        scene: 0,
        itemPos: {x: 0.59, y: 0.85},
        itemShadowDir: [-0.7, 0.4],
        itemShadowY: 0.85,
        avatarPos: {x: 0.55, y: 0.75},
        avatarShadowDir: [0.2, -0.3],
        avatarShadowY: 0.3,
        hitAreaOffset:  [-80, -70, 150, 250],
        size: 0.8,
        clickable: true,
        zOrder: 2,
        anchor: 0,
    },

    // {
    //     session: 'sand',
    //     name: 'sand',
    //     avatarAnim: 'doodled',
    //     itemPos: {x: 0.3, y: 0.95},
    //     avatarPos: {x: 0.3, y: 0.55},
    //     size: 0.8,
    //     zOrder: 0,
    //     hitAreaOffset:  [50, 250, 120, 120],
    //     scene: 1,
    //     anchor: 0.5,
    // },
    // {
    //     session: 'lake',
    //     name: 'lake',
    //     avatarAnim: 'fishing',
    //     itemPos: {x: 1.1, y: 1},
    //     avatarPos: {x: 0.6, y: 0.5},
    //     size: 0.7,
    //     clickable: true,
    //     zOrder: 2,
    //     hitAreaOffset:  [50, 250, 120, 120],
    //     scene: 1,
    //     anchor: 1,
    // },
    // {
    //     session: 'stool',
    //     name: 'stool',
    //     avatarAnim: 'pizza',
    //     itemPos: {x: 0.5, y: 0.85},
    //     avatarPos: {x: 0.5, y: 0.7},
    //     size: 0.8,
    //     clickable: true,
    //     zOrder: 0,
    //     hitAreaOffset:  [50, 250, 120, 120],
    //     scene: 1,
    //     anchor: 0.5,
    // },
    // {
    //     session: 'swing',
    //     name: 'swing',
    //     avatarAnim: 'swing',
    //     itemPos: {x: 0, y: 0.1},
    //     avatarPos: {x: 0.22, y: 0.6},
    //     size: 0.8,
    //     clickable: true,
    //     zOrder: 0,
    //     hitAreaOffset:  [50, 250, 120, 120],
    //     scene: 1,
    // },

];


const OTHERS = [
    {
        name:'letter',
        itemShadowDir: [-0.02, 1.02],
        itemShadowY: 1.1,
        scene: 0,
        itemPos: {x: 0.12, y: 0.09},
        size: 0.19,
        zOrder: 0,
        anchor: 0,
    }
]
    
export {ITEMS, OTHERS}